import ExcelJS from 'exceljs';
import { formatCurrency } from '@/utils/formatters';

export interface ExcelExportData {
  propertyInfo: {
    address: string;
    type: string;
    units: number;
    builtYear: number;
  };
  units: Array<{
    unitNumber: string;
    unitType: string;
    currentRent: number;
    recommendedRent?: number;
    change: number;
    annualImpact: number;
    status: string;
    reasoning?: string;
  }>;
  summary: {
    totalIncrease: number;
    affectedUnits: number;
    avgIncrease: number;
    riskLevel: string;
  };
  marketInsights?: {
    occupancyImpact: string;
    competitivePosition: string;
    timeToLease: string;
  };
}

export async function exportToExcel(data: ExcelExportData): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Property Optimization Tool';
  workbook.lastModifiedBy = 'Property Optimization Tool';
  workbook.created = new Date();
  workbook.modified = new Date();
  
  // Create main worksheet
  const worksheet = workbook.addWorksheet('Optimization Report', {
    headerFooter: {
      firstHeader: 'Property Optimization Report',
      firstFooter: '&CGenerated by Property Optimization Tool'
    }
  });
  
  // Set column widths
  worksheet.columns = [
    { header: 'Unit Number', key: 'unitNumber', width: 15 },
    { header: 'Unit Type', key: 'unitType', width: 15 },
    { header: 'Current Rent', key: 'currentRent', width: 15 },
    { header: 'Recommended Rent', key: 'recommendedRent', width: 18 },
    { header: 'Monthly Change', key: 'change', width: 15 },
    { header: 'Annual Impact', key: 'annualImpact', width: 15 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'Notes', key: 'notes', width: 40 }
  ];
  
  // Add title and property info
  const titleRow = worksheet.addRow(['Property Optimization Report']);
  titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: 'FF2563EB' } };
  titleRow.height = 30;
  
  worksheet.addRow(['Generated on:', new Date().toLocaleDateString()]);
  worksheet.addRow([]);
  
  // Property Information Section
  const propertyHeaderRow = worksheet.addRow(['Property Information']);
  propertyHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
  
  worksheet.addRow(['Address:', data.propertyInfo.address]);
  worksheet.addRow(['Property Type:', data.propertyInfo.type]);
  worksheet.addRow(['Total Units:', data.propertyInfo.units]);
  worksheet.addRow(['Built Year:', data.propertyInfo.builtYear]);
  worksheet.addRow([]);
  
  // Units Section Header
  const unitsHeaderRow = worksheet.addRow(['Unit-by-Unit Optimization']);
  unitsHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
  worksheet.addRow([]);
  
  // Add header row for units table
  const headerRow = worksheet.addRow([
    'Unit Number',
    'Unit Type', 
    'Current Rent',
    'Recommended Rent',
    'Monthly Change',
    'Annual Impact',
    'Status',
    'Notes'
  ]);
  
  // Style header row
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF3B82F6' }
    };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' }
    };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  });
  
  // Add unit data with conditional formatting
  data.units.forEach((unit) => {
    const row = worksheet.addRow([
      unit.unitNumber,
      unit.unitType,
      unit.currentRent,
      unit.recommendedRent || unit.currentRent,
      unit.change,
      unit.annualImpact,
      unit.status,
      unit.reasoning || 'No additional notes'
    ]);
    
    // Apply conditional formatting based on change amount
    const changeCell = row.getCell(5); // Monthly Change column
    const impactCell = row.getCell(6); // Annual Impact column
    
    if (unit.change > 0) {
      // Positive change - green
      changeCell.font = { color: { argb: 'FF059669' }, bold: true };
      changeCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFDCFCE7' }
      };
      impactCell.font = { color: { argb: 'FF059669' }, bold: true };
      impactCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFDCFCE7' }
      };
    } else if (unit.change < 0) {
      // Negative change - red
      changeCell.font = { color: { argb: 'FFDC2626' }, bold: true };
      changeCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFFEF2F2' }
      };
      impactCell.font = { color: { argb: 'FFDC2626' }, bold: true };
      impactCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFFEF2F2' }
      };
    } else {
      // No change - gray
      changeCell.font = { color: { argb: 'FF6B7280' } };
      impactCell.font = { color: { argb: 'FF6B7280' } };
    }
    
    // Add borders to all cells
    row.eachCell((cell) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
    
    // Format currency cells
    row.getCell(3).numFmt = '"$"#,##0.00'; // Current Rent
    row.getCell(4).numFmt = '"$"#,##0.00'; // Recommended Rent
    row.getCell(5).numFmt = '"$"#,##0.00'; // Monthly Change
    row.getCell(6).numFmt = '"$"#,##0.00'; // Annual Impact
  });
  
  worksheet.addRow([]);
  
  // Summary Section
  const summaryHeaderRow = worksheet.addRow(['Optimization Summary']);
  summaryHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
  
  const summaryData = [
    ['Total Annual Revenue Increase:', formatCurrency(data.summary.totalIncrease)],
    ['Units Affected:', data.summary.affectedUnits],
    ['Average Rent Increase:', `${data.summary.avgIncrease}%`],
    ['Risk Level:', data.summary.riskLevel]
  ];
  
  summaryData.forEach(([label, value]) => {
    const row = worksheet.addRow([label, value]);
    row.getCell(1).font = { bold: true };
    if (typeof label === 'string' && label.includes('Revenue Increase') && typeof value === 'string' && value.startsWith('$')) {
      row.getCell(2).font = { color: { argb: 'FF059669' }, bold: true };
    }
  });
  
  // Market Insights Section (if available)
  if (data.marketInsights) {
    worksheet.addRow([]);
    const insightsHeaderRow = worksheet.addRow(['Market Insights']);
    insightsHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
    
    worksheet.addRow(['Occupancy Impact:', data.marketInsights.occupancyImpact]);
    worksheet.addRow(['Competitive Position:', data.marketInsights.competitivePosition]);
    worksheet.addRow(['Time to Lease:', data.marketInsights.timeToLease]);
  }
  
  // Generate and download the file
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { 
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
  });
  
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.href = url;
  link.download = `property-optimization-${Date.now()}.xlsx`;
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
