import ExcelJS from 'exceljs';

export interface MarketAnalysisUnit {
  propertyType: 'Subject' | 'Competitor';
  propertyName: string;
  propertyAddress?: string;
  unitNumber?: string | null;
  floorPlanName?: string | null;
  unitType?: string;
  bedrooms: number;
  bathrooms?: number | null;
  squareFootage?: number | null;
  currentRent: number;
  aiRecommendedPrice?: number | null; // Only for subject properties
  newPrice?: number | null; // Only for subject properties  
  availabilityStatus: string;
  availabilityDate?: string | null;
  pricePerSqFt?: number | null;
}

export interface MarketAnalysisExportData {
  analysisName: string;
  generatedAt: string;
  filters: {
    bedroomTypes?: string[];
    priceRange?: { min: number; max: number };
    availability?: string;
    squareFootageRange?: { min: number; max: number };
  };
  units: MarketAnalysisUnit[];
  summary: {
    totalSubjectUnits: number;
    totalCompetitorUnits: number;
    avgSubjectRent: number;
    avgCompetitorRent: number;
    avgSubjectSqFt?: number;
    avgCompetitorSqFt?: number;
    marketDifference: number;
    marketDifferencePercent: number;
  };
}

// Helper function to format currency
function formatCurrency(value: number | null | undefined): string {
  if (value === null || value === undefined) {
    return '-';
  }
  return `$${value.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

// Helper function to format square footage
function formatSquareFootage(sqft: number | null | undefined): string {
  if (sqft === null || sqft === undefined) {
    return '-';
  }
  return sqft.toLocaleString() + ' sq ft';
}

// Helper function to format price per square foot
function formatPricePerSqFt(price: number | null | undefined): string {
  if (price === null || price === undefined) {
    return '-';
  }
  return `$${price.toFixed(2)}/sq ft`;
}

// Helper function to format availability date
function formatAvailabilityDate(date: string | null | undefined, status: string): string {
  if (!date || date === 'Contact for availability') {
    return status === 'available' ? 'Available Now' : 'Contact for availability';
  }
  
  const lowerDate = date.toLowerCase();
  
  if (lowerDate.includes('available now') || lowerDate.includes('immediately')) {
    return 'Available Now';
  }
  
  // Handle dates like "Oct 17" or "Dec 1"
  if (/^[A-Za-z]{3}\s+\d{1,2}$/.test(date)) {
    const currentYear = new Date().getFullYear();
    return `${date}, ${currentYear}`;
  }
  
  // Try to parse as a date
  try {
    const parsedDate = new Date(date);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate.toLocaleDateString('en-US', { 
        month: 'short', 
        day: 'numeric', 
        year: 'numeric' 
      });
    }
  } catch {
    // Fall back to original
  }
  
  return date;
}

export async function exportMarketAnalysisToExcel(data: MarketAnalysisExportData): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Rent AI Optimization';
  workbook.lastModifiedBy = 'Rent AI Optimization';
  workbook.created = new Date();
  workbook.modified = new Date();
  
  // Create main worksheet
  const worksheet = workbook.addWorksheet('Market Analysis', {
    headerFooter: {
      firstHeader: 'Market Analysis Report',
      firstFooter: '&CGenerated by Rent AI Optimization'
    }
  });
  
  // Set column widths
  worksheet.columns = [
    { header: 'Property Type', key: 'propertyType', width: 15 },
    { header: 'Property Name', key: 'propertyName', width: 30 },
    { header: 'Unit #', key: 'unitNumber', width: 12 },
    { header: 'Floor Plan', key: 'floorPlanName', width: 15 },
    { header: 'Type', key: 'unitType', width: 10 },
    { header: 'Bed', key: 'bedrooms', width: 8 },
    { header: 'Bath', key: 'bathrooms', width: 8 },
    { header: 'Sq Ft', key: 'squareFootage', width: 12 },
    { header: 'Current Rent', key: 'currentRent', width: 15 },
    { header: 'AI Recommended', key: 'aiRecommendedPrice', width: 18 },
    { header: 'New Price', key: 'newPrice', width: 15 },
    { header: 'Availability', key: 'availabilityStatus', width: 15 },
    { header: 'Available Date', key: 'availabilityDate', width: 18 },
    { header: 'Price/Sq Ft', key: 'pricePerSqFt', width: 15 }
  ];
  
  // Add title
  const titleRow = worksheet.addRow(['Market Analysis Report']);
  titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: 'FF2563EB' } };
  titleRow.height = 30;
  worksheet.mergeCells('A1:N1');
  
  // Add metadata
  worksheet.addRow(['Analysis Name:', data.analysisName]);
  worksheet.addRow(['Generated on:', data.generatedAt]);
  worksheet.addRow([]);
  
  // Add filters section if filters are applied
  if (data.filters && Object.keys(data.filters).length > 0) {
    const filtersHeaderRow = worksheet.addRow(['Applied Filters']);
    filtersHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
    
    if (data.filters.bedroomTypes && data.filters.bedroomTypes.length > 0) {
      worksheet.addRow(['Bedroom Types:', data.filters.bedroomTypes.join(', ')]);
    }
    if (data.filters.priceRange) {
      worksheet.addRow(['Price Range:', `$${data.filters.priceRange.min} - $${data.filters.priceRange.max}`]);
    }
    if (data.filters.availability) {
      worksheet.addRow(['Availability:', data.filters.availability]);
    }
    if (data.filters.squareFootageRange) {
      worksheet.addRow(['Square Footage:', `${data.filters.squareFootageRange.min} - ${data.filters.squareFootageRange.max} sq ft`]);
    }
    worksheet.addRow([]);
  }
  
  // Add summary section
  const summaryHeaderRow = worksheet.addRow(['Market Summary']);
  summaryHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
  
  worksheet.addRow(['Total Subject Units:', data.summary.totalSubjectUnits]);
  worksheet.addRow(['Total Competitor Units:', data.summary.totalCompetitorUnits]);
  worksheet.addRow(['Average Subject Rent:', formatCurrency(data.summary.avgSubjectRent)]);
  worksheet.addRow(['Average Competitor Rent:', formatCurrency(data.summary.avgCompetitorRent)]);
  
  if (data.summary.avgSubjectSqFt !== undefined) {
    worksheet.addRow(['Average Subject Sq Ft:', formatSquareFootage(data.summary.avgSubjectSqFt)]);
  }
  if (data.summary.avgCompetitorSqFt !== undefined) {
    worksheet.addRow(['Average Competitor Sq Ft:', formatSquareFootage(data.summary.avgCompetitorSqFt)]);
  }
  
  const diffPercent = data.summary.marketDifferencePercent;
  const diffText = diffPercent > 0 
    ? `+${diffPercent.toFixed(1)}% above market`
    : diffPercent < 0 
    ? `${Math.abs(diffPercent).toFixed(1)}% below market`
    : 'At market rate';
  worksheet.addRow(['Market Position:', diffText]);
  worksheet.addRow([]);
  
  // Add units data header
  const unitsHeaderRow = worksheet.addRow(['Unit-Level Comparison']);
  unitsHeaderRow.getCell(1).font = { size: 14, bold: true, color: { argb: 'FF059669' } };
  worksheet.addRow([]);
  
  // Add column headers
  const headerRow = worksheet.addRow([
    'Property Type',
    'Property Name',
    'Unit #',
    'Floor Plan',
    'Type',
    'Bed',
    'Bath',
    'Sq Ft',
    'Current Rent',
    'AI Recommended',
    'New Price',
    'Availability',
    'Available Date',
    'Price/Sq Ft'
  ]);
  
  // Style header row
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF3B82F6' }
    };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      right: { style: 'thin' },
      bottom: { style: 'thin' }
    };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
  });
  
  // Add unit data rows
  data.units.forEach((unit, index) => {
    const row = worksheet.addRow({
      propertyType: unit.propertyType,
      propertyName: unit.propertyName,
      unitNumber: unit.unitNumber || unit.floorPlanName || '-',
      floorPlanName: unit.floorPlanName || '-',
      unitType: unit.unitType || '-',
      bedrooms: unit.bedrooms,
      bathrooms: unit.bathrooms || '-',
      squareFootage: formatSquareFootage(unit.squareFootage),
      currentRent: formatCurrency(unit.currentRent),
      aiRecommendedPrice: unit.propertyType === 'Subject' && unit.aiRecommendedPrice 
        ? formatCurrency(unit.aiRecommendedPrice) 
        : '-',
      newPrice: unit.propertyType === 'Subject' && unit.newPrice 
        ? formatCurrency(unit.newPrice) 
        : '-',
      availabilityStatus: unit.availabilityStatus,
      availabilityDate: formatAvailabilityDate(unit.availabilityDate, unit.availabilityStatus),
      pricePerSqFt: formatPricePerSqFt(unit.pricePerSqFt)
    });
    
    // Style the row based on property type
    const bgColor = unit.propertyType === 'Subject' 
      ? { argb: 'FFF0F9FF' } // Light blue for subject
      : index % 2 === 0 
      ? { argb: 'FFF9FAFB' } // Light gray for competitor (even rows)
      : { argb: 'FFFFFFFF' }; // White for competitor (odd rows)
    
    row.eachCell((cell) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: bgColor
      };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        left: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        right: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } }
      };
    });
    
    // Highlight the property type column
    if (unit.propertyType === 'Subject') {
      row.getCell('propertyType').font = { bold: true, color: { argb: 'FF2563EB' } };
    }
    
    // Highlight AI recommended and new price columns for subject properties
    if (unit.propertyType === 'Subject' && unit.aiRecommendedPrice) {
      row.getCell('aiRecommendedPrice').font = { bold: true, color: { argb: 'FF059669' } };
    }
    if (unit.propertyType === 'Subject' && unit.newPrice) {
      row.getCell('newPrice').font = { bold: true, color: { argb: 'FF059669' } };
    }
  });
  
  // Auto-fit columns to content (with max width)
  worksheet.columns.forEach(column => {
    if (column.width) {
      let maxLength = column.width;
      column.eachCell?.({ includeEmpty: false }, (cell) => {
        const columnLength = cell.value ? cell.value.toString().length : 10;
        if (columnLength > maxLength) {
          maxLength = Math.min(columnLength, 50); // Cap at 50 characters
        }
      });
      column.width = maxLength + 2;
    }
  });
  
  // Generate Excel file
  const buffer = await workbook.xlsx.writeBuffer();
  
  // Create download
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `market-analysis-${new Date().toISOString().split('T')[0]}.xlsx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}